title: PRATHAM
description: Machine Learning Engineer
baseurl:
url:

theme: hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
